[theme]
base="dark"
primaryColor="#00ff9f"          # vivid neon-mint accent
backgroundColor="#000000"       # true black backdrop
secondaryBackgroundColor="#0a0a0a" 
textColor="#d7fbe8"             # soft green-white text
font="sans serif"
